<?php

declare(strict_types=1);

namespace Nowo\PwaBundle\DependencyInjection\Configuration;

use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;

/**
 * Web App Manifest configuration tree (W3C + common extensions).
 */
final class ManifestNodeDefinition
{
    public static function configure(ArrayNodeDefinition $node): void
    {
        $node
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('name')->defaultValue('My Application')->cannotBeEmpty()->end()
                ->scalarNode('short_name')->defaultValue('App')->cannotBeEmpty()->end()
                ->scalarNode('description')->defaultValue('')->end()
                ->scalarNode('lang')->defaultValue('en')->end()
                ->enumNode('dir')->values(['ltr', 'rtl', 'auto'])->defaultValue('ltr')->end()
                ->scalarNode('start_url')->defaultValue('/')->cannotBeEmpty()->end()
                ->booleanNode('absolute_start_url')->defaultTrue()->end()
                ->scalarNode('scope')->defaultValue('/')->cannotBeEmpty()->end()
                ->scalarNode('id')->defaultValue('/')->cannotBeEmpty()->end()
                ->enumNode('display')
                    ->values(['fullscreen', 'standalone', 'minimal-ui', 'browser'])
                    ->defaultValue('standalone')
                ->end()
                ->arrayNode('display_override')
                    ->defaultValue([])
                    ->scalarPrototype()
                        ->validate()
                            ->ifNotInArray(['fullscreen', 'standalone', 'minimal-ui', 'browser', 'window-controls-overlay'])
                            ->thenInvalid('Invalid display_override value %s')
                        ->end()
                    ->end()
                ->end()
                ->enumNode('orientation')
                    ->values(['any', 'natural', 'landscape', 'portrait', 'portrait-primary', 'portrait-secondary', 'landscape-primary', 'landscape-secondary'])
                    ->defaultValue('any')
                ->end()
                ->scalarNode('theme_color')->defaultValue('#0f172a')->end()
                ->scalarNode('background_color')->defaultValue('#ffffff')->end()
                ->variableNode('categories')->defaultValue([])->end()
                ->scalarNode('iarc_rating_id')->defaultNull()->end()
                ->booleanNode('prefer_related_applications')->defaultFalse()->end()
                ->arrayNode('icons')
                    ->defaultValue([])
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('src')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('sizes')->defaultValue('192x192')->end()
                            ->scalarNode('type')->defaultValue('image/png')->end()
                            ->scalarNode('purpose')->defaultValue('any')->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('screenshots')
                    ->defaultValue([])
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('src')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('sizes')->defaultValue('1280x720')->end()
                            ->scalarNode('type')->defaultValue('image/png')->end()
                            ->scalarNode('label')->defaultNull()->end()
                            ->enumNode('form_factor')->values(['narrow', 'wide'])->defaultNull()->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('shortcuts')
                    ->defaultValue([])
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('name')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('short_name')->defaultNull()->end()
                            ->scalarNode('url')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('description')->defaultNull()->end()
                            ->arrayNode('icons')
                                ->defaultValue([])
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('src')->isRequired()->cannotBeEmpty()->end()
                                        ->scalarNode('sizes')->defaultValue('96x96')->end()
                                        ->scalarNode('type')->defaultValue('image/png')->end()
                                        ->scalarNode('purpose')->defaultValue('any')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('related_applications')
                    ->defaultValue([])
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('platform')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('url')->defaultNull()->end()
                            ->scalarNode('id')->defaultNull()->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('scope_extensions')
                    ->defaultValue([])
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('origin')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('type')->defaultValue('origin')->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('launch_handler')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('client_mode')
                            ->values(['auto', 'navigate-existing', 'navigate-new', 'focus-existing'])
                            ->defaultValue('auto')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('protocol_handlers')
                    ->defaultValue([])
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('protocol')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('url')->isRequired()->cannotBeEmpty()->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('file_handlers')
                    ->defaultValue([])
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('action')->isRequired()->cannotBeEmpty()->end()
                            ->variableNode('accept_map')->defaultValue([])->end()
                            ->arrayNode('icons')
                                ->defaultValue([])
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('src')->isRequired()->cannotBeEmpty()->end()
                                        ->scalarNode('sizes')->defaultValue('96x96')->end()
                                        ->scalarNode('type')->defaultValue('image/png')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('share_target')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('action')->defaultNull()->end()
                        ->enumNode('method')->values(['GET', 'POST'])->defaultValue('GET')->end()
                        ->enumNode('enctype')->values(['application/x-www-form-urlencoded', 'multipart/form-data'])->defaultNull()->end()
                        ->arrayNode('params')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('title')->defaultNull()->end()
                                ->scalarNode('text')->defaultNull()->end()
                                ->scalarNode('url')->defaultNull()->end()
                                ->scalarNode('files')->defaultNull()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('edge_side_panel')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('preferred_width')->defaultNull()->end()
                    ->end()
                ->end()
            ->end();
    }
}
